#!/bin/sh

set -e

die() {
	echo "$@" 1>&2
	exit 1
}

[ "$1" = '' ] && die 'Missing event'

conf=$HOME/.ifttt.json

[ ! -f "$conf" ] && die "Missing configuration file: $conf"

mode=$(stat -c '%a' "$conf")
[ "$mode" -ne 600 -a "$mode" -ne 400 ] && \
	die "$conf must have 600 or 400 permissions"

apiKey=$(<"$conf" jq -r .api_key)

[ "$apiKey" = 'null' -o "$apiKey" = '' ] && die 'Missing API key'

event=$1
payload='{}'
index=1

shift
until [ "$1" = '' -o $index -gt 3 ]; do
	payload=$(
		echo $payload | jq -c --arg value "$1" ". + { value$index: \$value }"
	)

	shift
	index=$((index + 1))
done

echo "$payload" | curl \
	-sS --output /dev/null \
	-H 'Content-Type: application/json' \
	--data @- \
	"https://maker.ifttt.com/trigger/$event/with/key/$apiKey"
